version: '3.8'
services:
  backend-server:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    depends_on:
      - database
    ports:
      - 3000:3000
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dockerdb_pd2021